-- MySQL Script generated by MySQL Workbench
-- Sun Dec 13 13:58:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test_samson
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test_samson
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_samson` DEFAULT CHARACTER SET utf8 ;
USE `test_samson` ;

-- -----------------------------------------------------
-- Table `test_samson`.`a_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_samson`.`a_category` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `code_category` INT NOT NULL,
  `name_category` VARCHAR(45) NOT NULL,
  `parent_category_id` INT NOT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_samson`.`a_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_samson`.`a_product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `code_product` INT NOT NULL,
  `name_product` VARCHAR(45) NOT NULL,
  `a_category_id_category` INT NOT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `fk_a_product_a_category_idx` (`a_category_id_category` ASC) VISIBLE,
  CONSTRAINT `fk_a_product_a_category`
    FOREIGN KEY (`a_category_id_category`)
    REFERENCES `test_samson`.`a_category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_samson`.`a_property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_samson`.`a_property` (
  `id_property` INT NOT NULL AUTO_INCREMENT,
  `product` VARCHAR(45) NOT NULL,
  `property value` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_property`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_samson`.`a_ price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_samson`.`a_ price` (
  `id_price` INT NOT NULL AUTO_INCREMENT,
  `link product` VARCHAR(45) NOT NULL,
  `type price` VARCHAR(45) NOT NULL,
  `price` DECIMAL(100) NOT NULL,
  PRIMARY KEY (`id_price`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
